const primary = require('./primary.json');
const { requireAllIndexed } = require('./utils');

module.exports = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    $comment: 'THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
    additionalProperties: primary.additionalProperties,
    properties: {
        $schema: { type: 'string' },
        ...primary.properties,
        ...require('./general.json').properties,
        ...requireAllIndexed(__dirname),
    },
    required: [...primary.required],
    type: primary.type,
};
